### ISSUE TITLE
App crashes on login

### ISSUE THREAD

**Issue by hetvos** [Gargaj/BlueWP#2]
I built an AppX using VS2017 and installed it on my Microsoft Lumia 650, and upon trying to log in the app just crashes

**Comment by hetvos** [comment]
To cover all bases I deployed it directly to the device using Visual Studio and it does the same thing

**Comment by Gargaj** [comment]
Got a callstack / exception log?

**Comment by hetvos** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlueWP.ATProto.Client.<RequestAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BlueWP.ATProto.Client.<PostAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BlueWP.ATProto.Client.<AuthenticateWithPassword>d__11.MoveNext()
```

**Comment by Gargaj** [comment]
Thanks; could you check if https://github.com/Gargaj/BlueWP/commit/3b028054a307f04cd3e18a35f1ae4e7599d8a74b fixes it?

**Comment by hetvos** [comment]
Yeah! just posted from it and everything! (btw to build an appx package to upload, right click on the `BlueWP.App` project -> `Store` -> `Create App Packages`)

**Comment by Gargaj** [comment]
Yeah I just built one, gonna upload in a second, and figure out if it's possible to automate releases.
